#%RAML 1.0 NamedExample
{
  "name": "Trajan",
  "reign_start": "98 AD",
  "reign_end": "117 AD",
  "birth_date": "53 AD",
  "death_date": "117 AD",
  "dynasty": "Nerva-Antonine",
  "other_titles": "Caesar Nerva Traianus Augustus",
  "biography": "Trajan was the thirteenth Roman emperor, ruling from 98 AD until his death in 117 AD. He presided over one of the greatest expansions of the Roman Empire."
}