#%RAML 1.0 NamedExample
{
  "name": "Domitian",
  "reign_start": "81 AD",
  "reign_end": "96 AD",
  "birth_date": "51 AD",
  "death_date": "96 AD",
  "dynasty": "Flavian",
  "other_titles": "Titus Flavius Caesar Domitianus Augustus",
  "biography": "Domitian was the eleventh Roman emperor, ruling from 81 AD until his assassination in 96 AD."
}