#%RAML 1.0 NamedExample
{
  "customerId": 3,
  "orderDate": "2024-12-03T09:45:00Z",
  "shippingAddress": "789 Pine Street, TX",
  "billingAddress": "789 Pine Street, TX",
  "totalAmount": 75.00,
  "orderStatus": "Delivered",
  "paymentMethod": "Credit Card",
  "shippingMethod": "Standard"
}

