#%RAML 1.0 NamedExample
{
  "orderId": 101,
  "customerId": 1,
  "orderDate": "2024-12-01T14:23:00Z",
  "shippingAddress": "123 Elm Street, NY",
  "billingAddress": "123 Elm Street, NY",
  "totalAmount": 250.50,
  "orderStatus": "Pending",
  "paymentMethod": "Credit Card",
  "shippingMethod": "Standard"
}  