#%RAML 1.0 NamedExample
{
  "customerId": 4,
  "orderDate": "2024-12-04T16:00:00Z",
  "shippingAddress": "321 Maple Street, WA",
  "billingAddress": "321 Maple Street, WA",
  "totalAmount": 180.20,
  "orderStatus": "Cancelled",
  "paymentMethod": "Credit Card",
  "shippingMethod": "Standard"
}
