#%RAML 1.0 NamedExample
{
  "orderId": 102,
  "customerId": 2,
  "orderDate": "2024-12-02T11:10:00Z",
  "shippingAddress": "456 Oak Street, CA",
  "billingAddress": "456 Oak Street, CA",
  "totalAmount": 125.99,
  "orderStatus": "Shipped",
  "paymentMethod": "PayPal",
  "shippingMethod": "Express"
}